
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 2;
  public static final int DATUSE = 19;
  public static final int COMID = 15;
  public static final int IGUAL = 8;
  public static final int DECIMAL = 24;
  public static final int CORCHEC = 13;
  public static final int EXCLA = 5;
  public static final int CORCHEA = 12;
  public static final int XSON = 6;
  public static final int ID = 25;
  public static final int COMA = 14;
  public static final int NOMBRE = 22;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int INSTITUCION = 23;
  public static final int PASSWORD = 21;
  public static final int LLAVESC = 11;
  public static final int USUARIO = 20;
  public static final int USENU = 18;
  public static final int LLAVESA = 10;
  public static final int error = 1;
  public static final int FINSO = 17;
  public static final int VERSION = 7;
  public static final int INTER = 4;
  public static final int DOSPTS = 9;
  public static final int VALOR = 26;
  public static final int RESO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR",
  "MAYOR",
  "INTER",
  "EXCLA",
  "XSON",
  "VERSION",
  "IGUAL",
  "DOSPTS",
  "LLAVESA",
  "LLAVESC",
  "CORCHEA",
  "CORCHEC",
  "COMA",
  "COMID",
  "RESO",
  "FINSO",
  "USENU",
  "DATUSE",
  "USUARIO",
  "PASSWORD",
  "NOMBRE",
  "INSTITUCION",
  "DECIMAL",
  "ID",
  "VALOR"
  };
}

